name: Publish release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Gradle cache
              uses: actions/cache@v2
              with:
                  path: |
                      ~/.gradle/cache
                      ~/.gradle/wrapper
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-
            - name: Inflate secrets
              run: |
                echo "signing.keyId=${{ secrets.GPG_KEY_ID }}" >> gradle.properties
                echo "signing.password=${{ secrets.GPG_PASSWORD }}" >> gradle.properties
                echo "signing.secretKeyRingFile=${{ github.workspace }}/webasyst.gpg" >> gradle.properties
                echo "${{ secrets.GPG_KEYRING }}" | base64 --decode --ignore-garbage > webasyst.gpg
                cat gradle.properties
            - name: Release
              env:
                SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
                SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
              run: ./gradlew publish --no-daemon --no-parallel
